# Generated by Django 5.2.7 on 2025-12-04 20:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Template name", max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("alert", "Alert"),
                            ("reminder", "Reminder"),
                            ("social", "Social"),
                            ("marketing", "Marketing"),
                            ("emergency", "Emergency"),
                            ("iot_alert", "IoT Alert"),
                            ("crop_disease", "Crop Disease"),
                            ("weather", "Weather"),
                            ("marketplace", "Marketplace"),
                            ("payment", "Payment"),
                            ("learning", "Learning"),
                            ("community", "Community"),
                        ],
                        help_text="Type of notification this template is for",
                        max_length=20,
                    ),
                ),
                ("title_template", models.CharField(help_text="Title template with placeholders", max_length=200)),
                ("message_template", models.TextField(help_text="Message template with placeholders")),
                ("email_subject_template", models.CharField(blank=True, help_text="Email subject template", max_length=200)),
                ("email_body_template", models.TextField(blank=True, help_text="Email body template (HTML)")),
                ("sms_template", models.CharField(blank=True, help_text="SMS template (160 chars max)", max_length=160)),
                ("default_channels", models.JSONField(default=list, help_text="Default channels for this template")),
                (
                    "default_priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (5, "Normal"), (8, "High"), (10, "Critical")],
                        default=5,
                        help_text="Default priority for this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this template is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="Notification title", max_length=200)),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("alert", "Alert"),
                            ("reminder", "Reminder"),
                            ("social", "Social"),
                            ("marketing", "Marketing"),
                            ("emergency", "Emergency"),
                            ("iot_alert", "IoT Alert"),
                            ("crop_disease", "Crop Disease"),
                            ("weather", "Weather"),
                            ("marketplace", "Marketplace"),
                            ("payment", "Payment"),
                            ("learning", "Learning"),
                            ("community", "Community"),
                        ],
                        default="system",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (5, "Normal"), (8, "High"), (10, "Critical")],
                        default=5,
                        help_text="Notification priority (1-10)",
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, help_text="Additional notification data")),
                (
                    "action_url",
                    models.URLField(blank=True, help_text="URL to navigate to when notification is clicked", null=True),
                ),
                ("channels", models.JSONField(default=list, help_text="List of delivery channels to use")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When to send the notification (null for immediate)", null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, help_text="When the notification expires", null=True)),
                ("is_read", models.BooleanField(default=False, help_text="Whether the user has read this notification")),
                ("read_at", models.DateTimeField(blank=True, help_text="When the notification was read", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Target user for this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket"),
                            ("push", "Push Notification"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App"),
                        ],
                        help_text="Delivery channel used",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, help_text="External service message ID", max_length=200, null=True),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if delivery failed", null=True)),
                ("retry_count", models.IntegerField(default=0, help_text="Number of retry attempts")),
                ("sent_at", models.DateTimeField(blank=True, help_text="When the message was sent", null=True)),
                ("delivered_at", models.DateTimeField(blank=True, help_text="When the message was delivered", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="notifications.notification"
                    ),
                ),
            ],
            options={
                "db_table": "notification_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enable_websocket", models.BooleanField(default=True, help_text="Enable real-time WebSocket notifications")),
                ("enable_push", models.BooleanField(default=True, help_text="Enable push notifications")),
                ("enable_email", models.BooleanField(default=True, help_text="Enable email notifications")),
                ("enable_sms", models.BooleanField(default=False, help_text="Enable SMS notifications")),
                ("notification_types", models.JSONField(default=dict, help_text="Preferences for each notification type")),
                ("dnd_enabled", models.BooleanField(default=False, help_text="Enable do not disturb mode")),
                ("dnd_start_time", models.TimeField(blank=True, help_text="Do not disturb start time", null=True)),
                ("dnd_end_time", models.TimeField(blank=True, help_text="Do not disturb end time", null=True)),
                ("fcm_tokens", models.JSONField(blank=True, default=list, help_text="Firebase Cloud Messaging tokens")),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="Phone number for SMS notifications", max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notification_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "-created_at"], name="notificatio_user_id_611c58_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type", "-created_at"], name="notificatio_notific_498289_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["priority", "-created_at"], name="notificatio_priorit_b3d0b6_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["is_read", "-created_at"], name="notificatio_is_read_595d11_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["scheduled_at"], name="notificatio_schedul_2a5c00_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["expires_at"], name="notificatio_expires_66996e_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["notification", "channel"], name="notificatio_notific_31045d_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status", "-created_at"], name="notificatio_status_92d529_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["channel", "status"], name="notificatio_channel_169003_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="notificationdelivery",
            unique_together={("notification", "channel")},
        ),
    ]
