# Generated by Django 5.2.7 on 2025-10-23 14:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('conversation_type', models.CharField(choices=[('general', 'General Chat'), ('farming_advice', 'Farming Advice'), ('crop_diagnosis', 'Crop Diagnosis'), ('market_info', 'Market Information'), ('weather', 'Weather Inquiry'), ('pest_control', 'Pest Control'), ('fertilizer', 'Fertilizer Advice'), ('irrigation', 'Irrigation Guidance'), ('livestock', 'Livestock Care'), ('financial', 'Financial Planning')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context for the conversation')),
                ('language', models.CharField(default='en', max_length=10)),
                ('message_count', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image Message'), ('voice', 'Voice Message'), ('file', 'File Attachment'), ('location', 'Location Share'), ('recommendation', 'AI Recommendation'), ('error', 'Error Message')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata')),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='chat_voice/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('crops', 'Crop Information'), ('pests', 'Pest Management'), ('diseases', 'Disease Management'), ('fertilizers', 'Fertilizers'), ('irrigation', 'Irrigation'), ('weather', 'Weather Patterns'), ('market', 'Market Information'), ('equipment', 'Farm Equipment'), ('livestock', 'Livestock Care'), ('financial', 'Financial Planning'), ('general', 'General Farming')], max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Search tags')),
                ('language', models.CharField(default='en', max_length=10)),
                ('region_specific', models.CharField(blank=True, help_text='Specific to a region/country', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('accuracy_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['category'], name='ai_assistan_categor_579362_idx'), models.Index(fields=['language'], name='ai_assistan_languag_9f90ed_idx'), models.Index(fields=['is_active'], name='ai_assistan_is_acti_5af4f9_idx'), models.Index(fields=['tags'], name='ai_assistan_tags_d85da7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_audio', models.FileField(upload_to='voice_input/')),
                ('output_audio', models.FileField(blank=True, null=True, upload_to='voice_output/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('language_detected', models.CharField(blank=True, max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('transcription_time_ms', models.IntegerField(blank=True, null=True)),
                ('response_generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('synthesis_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_interactions', to='ai_assistant.chatconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('crop_selection', 'Crop Selection'), ('planting_schedule', 'Planting Schedule'), ('fertilizer', 'Fertilizer Recommendation'), ('pest_control', 'Pest Control'), ('irrigation', 'Irrigation Schedule'), ('harvest_timing', 'Harvest Timing'), ('market_opportunity', 'Market Opportunity'), ('weather_action', 'Weather-based Action'), ('financial_advice', 'Financial Advice'), ('equipment', 'Equipment Recommendation'), ('general_farming', 'General Farming Tip')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detailed_content', models.JSONField(default=dict, help_text='Detailed recommendation data')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('reasoning', models.TextField(blank=True, help_text='AI reasoning for this recommendation')),
                ('trigger_data', models.JSONField(default=dict, help_text='Data that triggered this recommendation')),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('best_implementation_date', models.DateField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='farms.crop')),
                ('context_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='ai_assistan_user_id_6712de_idx'), models.Index(fields=['recommendation_type'], name='ai_assistan_recomme_0adc72_idx'), models.Index(fields=['status'], name='ai_assistan_status_ae8639_idx'), models.Index(fields=['priority'], name='ai_assistan_priorit_4c84e7_idx'), models.Index(fields=['created_at'], name='ai_assistan_created_a6f698_idx'), models.Index(fields=['valid_until'], name='ai_assistan_valid_u_38f0f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conversations_started', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('voice_interactions', models.IntegerField(default=0)),
                ('recommendations_received', models.IntegerField(default=0)),
                ('recommendations_implemented', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('crop_diagnosis_queries', models.IntegerField(default=0)),
                ('market_info_queries', models.IntegerField(default=0)),
                ('weather_queries', models.IntegerField(default=0)),
                ('farming_advice_queries', models.IntegerField(default=0)),
                ('average_response_time_ms', models.FloatField(blank=True, null=True)),
                ('user_satisfaction_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='ai_assistan_user_id_739314_idx'), models.Index(fields=['date'], name='ai_assistan_date_457818_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user'], name='ai_assistan_user_id_5094fa_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['conversation_type'], name='ai_assistan_convers_e717a7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status'], name='ai_assistan_status_02cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_3d704f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['last_message_at'], name='ai_assistan_last_me_e61963_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation'], name='ai_assistan_convers_8fcc14_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='ai_assistan_role_f242d3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='ai_assistan_message_078387_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_817c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['user'], name='ai_assistan_user_id_5402df_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['conversation'], name='ai_assistan_convers_5a370a_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['status'], name='ai_assistan_status_f56212_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_f508c0_idx'),
        ),
    ]
