# Generated by Django 5.2.7 on 2025-12-05 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageQuota",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quota_limit", models.BigIntegerField(default=1073741824)),
                ("used_storage", models.BigIntegerField(default=0)),
                ("max_files", models.IntegerField(default=1000)),
                ("file_count", models.IntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="storage_quota", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "storage_quotas",
            },
        ),
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("DOCUMENT", "Document"),
                            ("AUDIO", "Audio"),
                            ("ARCHIVE", "Archive"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("file_hash", models.CharField(help_text="SHA-256 hash", max_length=64)),
                ("storage_path", models.CharField(max_length=500)),
                ("storage_backend", models.CharField(default="s3", max_length=50)),
                ("bucket_name", models.CharField(blank=True, max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                ("access_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("PROCESSING", "Processing"),
                            ("AVAILABLE", "Available"),
                            ("ARCHIVED", "Archived"),
                            ("DELETED", "Deleted"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        default="UPLOADING",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCANNING", "Scanning"),
                            ("CLEAN", "Clean"),
                            ("INFECTED", "Infected"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("scan_result", models.JSONField(blank=True, default=dict)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stored_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("THUMBNAIL", "Thumbnail"),
                            ("SMALL", "Small"),
                            ("MEDIUM", "Medium"),
                            ("LARGE", "Large"),
                            ("ORIGINAL", "Original"),
                        ],
                        max_length=20,
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("file_size", models.BigIntegerField()),
                ("storage_path", models.CharField(max_length=500)),
                ("file_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="file_storage.storedfile"
                    ),
                ),
            ],
            options={
                "db_table": "image_variants",
                "ordering": ["variant_type"],
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("DOWNLOAD", "Download"), ("VIEW", "View"), ("SHARE", "Share"), ("DELETE", "Delete")],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="access_logs", to="file_storage.storedfile"
                    ),
                ),
            ],
            options={
                "db_table": "file_access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkedUpload",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("upload_id", models.CharField(max_length=255, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("chunk_size", models.IntegerField(default=5242880)),
                ("total_chunks", models.IntegerField()),
                ("uploaded_chunks", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("storage_path", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("last_chunk_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunked_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_file",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="file_storage.storedfile"
                    ),
                ),
            ],
            options={
                "db_table": "chunked_uploads",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["uploaded_by", "status"], name="stored_file_uploade_011a4c_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["file_type", "status"], name="stored_file_file_ty_3dae29_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["file_hash"], name="stored_file_file_ha_773303_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["uploaded_at"], name="stored_file_uploade_4e4686_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["expires_at"], name="stored_file_expires_eefb3b_idx"),
        ),
        migrations.AddIndex(
            model_name="imagevariant",
            index=models.Index(fields=["original_file", "variant_type"], name="image_varia_origina_210dd6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="imagevariant",
            unique_together={("original_file", "variant_type")},
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(fields=["file", "accessed_at"], name="file_access_file_id_57ead1_idx"),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(fields=["user", "accessed_at"], name="file_access_user_id_dac85f_idx"),
        ),
        migrations.AddIndex(
            model_name="chunkedupload",
            index=models.Index(fields=["uploaded_by", "status"], name="chunked_upl_uploade_0f166a_idx"),
        ),
        migrations.AddIndex(
            model_name="chunkedupload",
            index=models.Index(fields=["upload_id"], name="chunked_upl_upload__08baa5_idx"),
        ),
        migrations.AddIndex(
            model_name="chunkedupload",
            index=models.Index(fields=["expires_at"], name="chunked_upl_expires_c235c6_idx"),
        ),
    ]
