# Generated by Django 5.2.7 on 2025-12-05 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationBody",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("accreditation_number", models.CharField(blank=True, max_length=100)),
                ("accreditation_body", models.CharField(blank=True, max_length=255)),
                ("accreditation_expiry", models.DateField(blank=True, null=True)),
                ("api_endpoint", models.URLField(blank=True)),
                ("api_key_encrypted", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("supported_certificate_types", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Certification Bodies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_number", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("organic", "Organic Certification"),
                            ("quality", "Quality Certification"),
                            ("origin", "Certificate of Origin"),
                            ("phytosanitary", "Phytosanitary Certificate"),
                            ("fair_trade", "Fair Trade Certification"),
                            ("gmp", "Good Manufacturing Practice"),
                            ("haccp", "HACCP Certification"),
                            ("custom", "Custom Certification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issuer", models.CharField(max_length=255)),
                ("issuer_id", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("product_category", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("issued", "Issued"),
                            ("verified", "Verified"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("blockchain_hash", models.CharField(db_index=True, max_length=66, unique=True)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("blockchain_network", models.CharField(default="ethereum", max_length=50)),
                ("qr_code", models.ImageField(blank=True, upload_to="certificates/qr/")),
                ("qr_code_data", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("verification_count", models.IntegerField(default=0)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateVerification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verifier_ip", models.GenericIPAddressField()),
                ("verifier_user_agent", models.TextField(blank=True)),
                ("is_valid", models.BooleanField()),
                ("verification_message", models.TextField()),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="verifications", to="blockchain.certificate"
                    ),
                ),
                (
                    "verifier_user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_id", models.CharField(db_index=True, max_length=100)),
                ("product_name", models.CharField(max_length=255)),
                ("batch_number", models.CharField(db_index=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("harvest", "Harvest"),
                            ("processing", "Processing"),
                            ("packaging", "Packaging"),
                            ("storage", "Storage"),
                            ("transport", "Transport"),
                            ("inspection", "Inspection"),
                            ("customs", "Customs Clearance"),
                            ("delivery", "Delivery"),
                            ("sale", "Sale"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_description", models.TextField()),
                ("event_timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("actor_name", models.CharField(max_length=255)),
                ("actor_role", models.CharField(max_length=100)),
                ("blockchain_hash", models.CharField(db_index=True, max_length=66, unique=True)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("previous_event_hash", models.CharField(blank=True, max_length=66)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chain_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["owner", "status"], name="blockchain__owner_i_8e9885_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["certificate_type", "status"], name="blockchain__certifi_40bea3_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["expiry_date"], name="blockchain__expiry__8a264c_idx"),
        ),
        migrations.AddIndex(
            model_name="supplychainevent",
            index=models.Index(fields=["product_id", "event_timestamp"], name="blockchain__product_04b702_idx"),
        ),
        migrations.AddIndex(
            model_name="supplychainevent",
            index=models.Index(fields=["batch_number", "event_timestamp"], name="blockchain__batch_n_0bd404_idx"),
        ),
        migrations.AddIndex(
            model_name="supplychainevent",
            index=models.Index(fields=["event_type"], name="blockchain__event_t_1b877c_idx"),
        ),
    ]
