# Generated by Django 5.2.7 on 2025-12-04 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("yield_prediction", "Yield Prediction"),
                            ("weather_forecast", "Weather Forecast"),
                            ("price_prediction", "Price Prediction"),
                            ("disease_detection", "Disease Detection"),
                            ("demand_forecast", "Demand Forecast"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("active", "Active"),
                            ("testing", "Testing"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("algorithm", models.CharField(blank=True, max_length=100)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("accuracy", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("precision", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("recall", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("f1_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("mae", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("rmse", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("training_data_size", models.IntegerField(default=0)),
                ("training_started_at", models.DateTimeField(blank=True, null=True)),
                ("training_completed_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["model_type", "status"], name="analytics_p_model_t_2972ce_idx"),
                    models.Index(fields=["status"], name="analytics_p_status_91e287_idx"),
                ],
                "unique_together": {("model_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("farm_performance", "Farm Performance"),
                            ("marketplace_stats", "Marketplace Statistics"),
                            ("user_activity", "User Activity"),
                            ("financial_summary", "Financial Summary"),
                            ("system_health", "System Health"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("is_cached", models.BooleanField(default=True)),
                ("cache_expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(fields=["metric_type", "user"], name="analytics_d_metric__0637e5_idx"),
                    models.Index(fields=["calculated_at"], name="analytics_d_calcula_0998f3_idx"),
                    models.Index(fields=["cache_expires_at"], name="analytics_d_cache_e_313657_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("recommendation", "Recommendation"),
                            ("warning", "Warning"),
                            ("opportunity", "Opportunity"),
                            ("alert", "Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("recommended_actions", models.JSONField(default=list)),
                ("context_data", models.JSONField(default=dict)),
                ("source_metric", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("is_acted_upon", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="insights", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="analytics_i_user_id_f091a8_idx"),
                    models.Index(fields=["priority"], name="analytics_i_priorit_a28697_idx"),
                    models.Index(fields=["created_at"], name="analytics_i_created_63b483_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("input_data", models.JSONField(default=dict)),
                ("prediction_value", models.JSONField(default=dict)),
                ("confidence_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("actual_value", models.JSONField(blank=True, default=dict, null=True)),
                ("is_accurate", models.BooleanField(blank=True, null=True)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="predictions", to="analytics.predictionmodel"
                    ),
                ),
            ],
            options={
                "ordering": ["-predicted_at"],
                "indexes": [
                    models.Index(fields=["model", "user"], name="analytics_p_model_i_65279a_idx"),
                    models.Index(fields=["predicted_at"], name="analytics_p_predict_a4b4f1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("farm_performance", "Farm Performance Report"),
                            ("financial_summary", "Financial Summary"),
                            ("crop_analysis", "Crop Analysis"),
                            ("marketplace_insights", "Marketplace Insights"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("excel", "Excel"), ("json", "JSON")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="analytics_r_user_id_ff8113_idx"),
                    models.Index(fields=["report_type"], name="analytics_r_report__06672b_idx"),
                    models.Index(fields=["created_at"], name="analytics_r_created_8263b2_idx"),
                ],
            },
        ),
    ]
