# Generated by Django 5.2.7 on 2025-12-04 19:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0002_field_crop_field_satelliteimagery_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "measurement_unit",
                    models.CharField(
                        choices=[
                            ("celsius", "Celsius (°C)"),
                            ("fahrenheit", "Fahrenheit (°F)"),
                            ("percent", "Percentage (%)"),
                            ("ppm", "Parts Per Million (ppm)"),
                            ("ph", "pH Level"),
                            ("lux", "Lux"),
                            ("pascal", "Pascal (Pa)"),
                            ("meter", "Meter (m)"),
                            ("mm", "Millimeter (mm)"),
                            ("ms", "Meter per Second (m/s)"),
                            ("degree", "Degree (°)"),
                            ("volt", "Volt (V)"),
                            ("ampere", "Ampere (A)"),
                            ("watt", "Watt (W)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("precision", models.IntegerField(default=2, help_text="Decimal places for readings")),
                ("default_min_threshold", models.FloatField(blank=True, null=True)),
                ("default_max_threshold", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sensor", "Sensor Device"),
                            ("actuator", "Actuator Device"),
                            ("gateway", "Gateway Device"),
                            ("hybrid", "Hybrid Device"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_number", models.CharField(max_length=50)),
                ("supported_sensors", models.JSONField(default=list, help_text="List of sensor types this device supports")),
                (
                    "communication_protocols",
                    models.JSONField(default=list, help_text="Supported communication protocols (WiFi, LoRa, etc.)"),
                ),
                (
                    "power_requirements",
                    models.JSONField(default=dict, help_text="Power consumption and battery specifications"),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=20)),
                ("update_url", models.URLField(blank=True, help_text="Firmware update endpoint")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["category"], name="iot_service_categor_c6f2d5_idx"),
                    models.Index(fields=["manufacturer"], name="iot_service_manufac_e28b41_idx"),
                    models.Index(fields=["is_active"], name="iot_service_is_acti_e559cc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(help_text="Unique device identifier", max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ("altitude", models.FloatField(blank=True, help_text="Altitude in meters", null=True)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("configuration", models.JSONField(default=dict, help_text="Device-specific configuration parameters")),
                ("sampling_interval", models.IntegerField(default=300, help_text="Data sampling interval in seconds")),
                (
                    "connectivity_type",
                    models.CharField(
                        choices=[
                            ("wifi", "WiFi"),
                            ("lora", "LoRa"),
                            ("cellular", "Cellular"),
                            ("ethernet", "Ethernet"),
                            ("bluetooth", "Bluetooth"),
                            ("zigbee", "ZigBee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("network_config", models.JSONField(default=dict, help_text="Network configuration (IP, gateway, etc.)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("error", "Error State"),
                            ("offline", "Offline"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery level percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True,
                        help_text="Signal strength in dBm",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-120),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=20)),
                ("last_firmware_update", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("maintenance_schedule", models.JSONField(default=dict, help_text="Maintenance schedule and history")),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="devices", to="iot_service.devicetype"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot_devices",
                        to="farms.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iot_devices",
                        to="farms.field",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="iot_devices", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(default=dict, help_text="Group-wide configuration settings")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="device_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("devices", models.ManyToManyField(blank=True, related_name="groups", to="iot_service.iotdevice")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("config_update", "Configuration Update"),
                            ("firmware_update", "Firmware Update"),
                            ("restart", "Restart Device"),
                            ("calibrate", "Calibrate Sensors"),
                            ("data_sync", "Sync Data"),
                            ("custom", "Custom Command"),
                        ],
                        max_length=20,
                    ),
                ),
                ("command_data", models.JSONField(help_text="Command parameters and data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Command expiration time")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commands", to="iot_service.iotdevice"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("raw_value", models.FloatField(blank=True, help_text="Raw sensor value before calibration", null=True)),
                (
                    "quality",
                    models.CharField(
                        choices=[("good", "Good"), ("fair", "Fair"), ("poor", "Poor"), ("invalid", "Invalid")],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional sensor metadata (calibration, environmental conditions, etc.)"
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sensor_readings", to="iot_service.iotdevice"
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="readings", to="iot_service.sensortype"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeviceAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Violation"),
                            ("device_offline", "Device Offline"),
                            ("low_battery", "Low Battery"),
                            ("sensor_failure", "Sensor Failure"),
                            ("connectivity", "Connectivity Issue"),
                            ("maintenance", "Maintenance Required"),
                            ("firmware", "Firmware Update Available"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict, help_text="Additional alert context and data")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="iot_service.iotdevice"
                    ),
                ),
                (
                    "sensor_reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="iot_service.sensorreading",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirmwareVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=20)),
                ("build_number", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField()),
                ("changelog", models.TextField(blank=True)),
                ("file_url", models.URLField(help_text="URL to firmware file")),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("checksum", models.CharField(help_text="SHA-256 checksum", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("testing", "Testing"),
                            ("stable", "Stable"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="development",
                        max_length=15,
                    ),
                ),
                ("min_hardware_version", models.CharField(blank=True, max_length=20)),
                (
                    "compatible_versions",
                    models.JSONField(default=list, help_text="List of compatible firmware versions for upgrade"),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmware_versions",
                        to="iot_service.devicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["device_type", "status"], name="iot_service_device__72b941_idx"),
                    models.Index(fields=["status"], name="iot_service_status_49ab34_idx"),
                    models.Index(fields=["released_at"], name="iot_service_release_bbf496_idx"),
                ],
                "unique_together": {("device_type", "version")},
            },
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["device_id"], name="iot_service_device__7383fb_idx"),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["owner"], name="iot_service_owner_i_ca9d6e_idx"),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["status"], name="iot_service_status_47fb5a_idx"),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["device_type"], name="iot_service_device__1682b7_idx"),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["last_seen"], name="iot_service_last_se_c3f791_idx"),
        ),
        migrations.AddIndex(
            model_name="iotdevice",
            index=models.Index(fields=["farm"], name="iot_service_farm_id_a7b6b4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="devicegroup",
            unique_together={("owner", "name")},
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["device", "status"], name="iot_service_device__17bfc0_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["command_type"], name="iot_service_command_813b18_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["status"], name="iot_service_status_f4a7e6_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(fields=["created_at"], name="iot_service_created_b3c322_idx"),
        ),
        migrations.AddIndex(
            model_name="devicealert",
            index=models.Index(fields=["device", "status"], name="iot_service_device__e228eb_idx"),
        ),
        migrations.AddIndex(
            model_name="devicealert",
            index=models.Index(fields=["alert_type"], name="iot_service_alert_t_953a95_idx"),
        ),
        migrations.AddIndex(
            model_name="devicealert",
            index=models.Index(fields=["severity"], name="iot_service_severit_0b4d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="devicealert",
            index=models.Index(fields=["status"], name="iot_service_status_e26bd8_idx"),
        ),
        migrations.AddIndex(
            model_name="devicealert",
            index=models.Index(fields=["created_at"], name="iot_service_created_8400c4_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["device", "timestamp"], name="iot_service_device__05b75b_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["sensor_type", "timestamp"], name="iot_service_sensor__c44679_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["timestamp"], name="iot_service_timesta_d6e7cf_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["received_at"], name="iot_service_receive_9d7807_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["quality"], name="iot_service_quality_4cbaab_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sensorreading",
            unique_together={("device", "sensor_type", "timestamp")},
        ),
    ]
