# Generated by Django 5.2.7 on 2025-12-05 19:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Course Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("thumbnail", models.URLField(blank=True)),
                ("preview_video", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("enrollment_count", models.IntegerField(default=0)),
                ("completion_count", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="courses_taught", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("prerequisites", models.ManyToManyField(blank=True, related_name="required_for", to="learning.course")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="learning.coursecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed"), ("dropped", "Dropped")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completed_lessons", models.IntegerField(default=0)),
                ("total_time_spent", models.IntegerField(default=0, help_text="Time in minutes")),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="learning.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="learning.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="course_reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review", to="learning.enrollment"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("verification_url", models.URLField(blank=True)),
                ("final_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("completion_time_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="certificate", to="learning.enrollment"
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("video", "Video"), ("article", "Article"), ("quiz", "Quiz"), ("assignment", "Assignment")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Article content or video description")),
                ("video_url", models.URLField(blank=True)),
                ("video_duration", models.IntegerField(default=0, help_text="Duration in seconds")),
                ("order", models.IntegerField(default=0)),
                ("is_free", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="learning.course"
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("time_spent", models.IntegerField(default=0, help_text="Time in seconds")),
                ("video_progress", models.IntegerField(default=0, help_text="Video progress in seconds")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lesson_progress", to="learning.enrollment"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="progress_records", to="learning.lesson"
                    ),
                ),
            ],
            options={
                "ordering": ["enrollment", "lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField()),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.IntegerField(help_text="Size in bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="learning.lesson"
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("is_answered", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_expert_answer", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="learning.question"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_accepted", "-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interest_score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_users",
                        to="learning.coursecategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-interest_score"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status", "-created_at"], name="learning_co_status_ee5079_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["category", "status"], name="learning_co_categor_95930a_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["difficulty"], name="learning_co_difficu_a64e53_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["user", "status"], name="learning_en_user_id_b55f06_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["course", "status"], name="learning_en_course__4bb6dd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["course", "is_approved"], name="learning_co_course__945ca8_idx"),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["-created_at"], name="learning_co_created_2ac3e2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="coursereview",
            unique_together={("course", "user")},
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["certificate_number"], name="learning_ce_certifi_26e67a_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["enrollment"], name="learning_ce_enrollm_1a8188_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["course", "order"], name="learning_le_course__30756f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "slug")},
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(fields=["enrollment", "is_completed"], name="learning_le_enrollm_bfbd33_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("enrollment", "lesson")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["course", "-created_at"], name="learning_qu_course__64199f_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["is_answered"], name="learning_qu_is_answ_5e2695_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question", "-created_at"], name="learning_an_questio_3575f3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together={("user", "category")},
        ),
    ]
