# Generated by Django 5.2.7 on 2025-10-23 15:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('common_names', models.JSONField(default=list, help_text='List of common names')),
                ('category', models.CharField(choices=[('fungal', 'Fungal Disease'), ('bacterial', 'Bacterial Disease'), ('viral', 'Viral Disease'), ('pest', 'Pest Damage'), ('nutrient', 'Nutrient Deficiency'), ('environmental', 'Environmental Stress'), ('genetic', 'Genetic Disorder')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Detailed symptoms description')),
                ('visual_indicators', models.JSONField(default=list, help_text='List of visual indicators')),
                ('affected_crops', models.JSONField(default=list, help_text='List of crops this disease affects')),
                ('typical_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('spread_rate', models.CharField(blank=True, help_text='How quickly it spreads', max_length=50)),
                ('seasonal_pattern', models.CharField(blank=True, max_length=100)),
                ('favorable_conditions', models.JSONField(default=dict, help_text='Environmental conditions that favor this disease')),
                ('prevention_methods', models.TextField(blank=True)),
                ('organic_treatments', models.TextField(blank=True)),
                ('chemical_treatments', models.TextField(blank=True)),
                ('reference_images', models.JSONField(default=list, help_text='URLs to reference images')),
                ('external_links', models.JSONField(default=list, help_text='External reference links')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence score for AI detection', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diseases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='crop_scans/')),
                ('image_metadata', models.JSONField(default=dict, help_text='Image metadata like size, format, GPS coordinates')),
                ('crop_type', models.CharField(blank=True, choices=[('tomato', 'Tomato'), ('potato', 'Potato'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('rice', 'Rice'), ('soybean', 'Soybean'), ('pepper', 'Pepper'), ('cucumber', 'Cucumber'), ('lettuce', 'Lettuce'), ('carrot', 'Carrot'), ('onion', 'Onion'), ('cabbage', 'Cabbage'), ('other', 'Other')], max_length=20)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('growth_stage', models.CharField(blank=True, max_length=50)),
                ('location_data', models.JSONField(default=dict, help_text='GPS coordinates, farm location, field information')),
                ('environmental_conditions', models.JSONField(default=dict, help_text='Weather, soil conditions, etc. at time of scan')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_review', 'Pending Review')], default='processing', max_length=20)),
                ('detected_diseases', models.JSONField(default=list, help_text='List of detected diseases with confidence scores')),
                ('health_score', models.FloatField(blank=True, help_text='Overall plant health score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('confidence_scores', models.JSONField(default=dict, help_text='Confidence scores for different aspects of analysis')),
                ('ai_recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('user_feedback', models.TextField(blank=True)),
                ('accuracy_rating', models.IntegerField(blank=True, help_text='User rating of scan accuracy (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('treatment_applied', models.JSONField(default=list, help_text='Treatments applied by user')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_scans', models.ManyToManyField(blank=True, related_name='original_scan', to='crop_detection.cropscan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_scans', to=settings.AUTH_USER_MODEL)),
                ('user_confirmed_disease', models.ForeignKey(blank=True, help_text='Disease confirmed by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_confirmed_scans', to='crop_detection.disease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('confidence_in_ai', models.IntegerField(help_text='Expert confidence in AI diagnosis (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_comments', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('corrected_health_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ai_accuracy_assessment', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('expert_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_diagnoses', to='crop_detection.disease')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__in': ['expert', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to=settings.AUTH_USER_MODEL)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_review', to='crop_detection.cropscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('successful_scans', models.IntegerField(default=0)),
                ('failed_scans', models.IntegerField(default=0)),
                ('diseases_detected', models.JSONField(default=dict, help_text='Count of each disease detected')),
                ('crops_scanned', models.JSONField(default=dict, help_text='Count of each crop type scanned')),
                ('average_accuracy_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_feedback_count', models.IntegerField(default=0)),
                ('average_health_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('health_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('first_scan_date', models.DateTimeField(blank=True, null=True)),
                ('last_scan_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('most_common_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_common_for_users', to='crop_detection.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scan histories',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('treatment_type', models.CharField(choices=[('preventive', 'Preventive'), ('curative', 'Curative'), ('supportive', 'Supportive'), ('emergency', 'Emergency')], max_length=20)),
                ('method', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical'), ('biological', 'Biological'), ('cultural', 'Cultural Practice'), ('mechanical', 'Mechanical'), ('integrated', 'Integrated Approach')], max_length=20)),
                ('description', models.TextField()),
                ('detailed_instructions', models.TextField()),
                ('application_method', models.TextField(blank=True)),
                ('timing', models.CharField(help_text='When to apply treatment', max_length=200)),
                ('frequency', models.CharField(help_text='How often to apply', max_length=100)),
                ('duration', models.CharField(help_text='Treatment duration', max_length=100)),
                ('materials_needed', models.JSONField(default=list, help_text='List of materials/chemicals needed')),
                ('dosage_instructions', models.TextField(blank=True)),
                ('effectiveness_rating', models.FloatField(help_text='Effectiveness rating (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('safety_precautions', models.TextField(blank=True)),
                ('environmental_impact', models.TextField(blank=True)),
                ('estimated_cost', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('suitable_crops', models.JSONField(default=list, help_text='Crops this treatment is suitable for')),
                ('weather_conditions', models.CharField(blank=True, max_length=200)),
                ('growth_stage', models.CharField(blank=True, max_length=100)),
                ('expected_results', models.TextField(blank=True)),
                ('success_indicators', models.JSONField(default=list)),
                ('is_recommended', models.BooleanField(default=True)),
                ('requires_expert', models.BooleanField(default=False, help_text='Requires expert consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='crop_detection.disease')),
            ],
            options={
                'ordering': ['-effectiveness_rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cropscan',
            name='recommended_treatments',
            field=models.ManyToManyField(blank=True, related_name='recommended_scans', to='crop_detection.treatment'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['category'], name='crop_detect_categor_d142dc_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='crop_detect_name_fa17d5_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['is_active'], name='crop_detect_is_acti_caf7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['typical_severity'], name='crop_detect_typical_f1589d_idx'),
        ),
        migrations.AddIndex(
            model_name='expertreview',
            index=models.Index(fields=['status'], name='crop_detect_status_522bec_idx'),
        ),
        migrations.AddIndex(
            model_name='expertreview',
            index=models.Index(fields=['reviewer'], name='crop_detect_reviewe_3c31f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expertreview',
            index=models.Index(fields=['created_at'], name='crop_detect_created_26b2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['disease'], name='crop_detect_disease_e92b17_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['treatment_type'], name='crop_detect_treatme_066b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['method'], name='crop_detect_method_579b63_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['effectiveness_rating'], name='crop_detect_effecti_8ade72_idx'),
        ),
        migrations.AddIndex(
            model_name='cropscan',
            index=models.Index(fields=['user'], name='crop_detect_user_id_005a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='cropscan',
            index=models.Index(fields=['status'], name='crop_detect_status_83dd46_idx'),
        ),
        migrations.AddIndex(
            model_name='cropscan',
            index=models.Index(fields=['crop_type'], name='crop_detect_crop_ty_436efa_idx'),
        ),
        migrations.AddIndex(
            model_name='cropscan',
            index=models.Index(fields=['created_at'], name='crop_detect_created_fc55e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cropscan',
            index=models.Index(fields=['health_score'], name='crop_detect_health__a4f554_idx'),
        ),
    ]
