# Generated by Django 5.2.7 on 2025-12-05 18:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("country_code", models.CharField(max_length=3)),
                ("product_category", models.CharField(blank=True, max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("REQUIRED_FIELD", "Required Field"),
                            ("VALUE_RANGE", "Value Range"),
                            ("FORMAT_VALIDATION", "Format Validation"),
                            ("DOCUMENT_REQUIRED", "Document Required"),
                            ("CERTIFICATION_REQUIRED", "Certification Required"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rule_name", models.CharField(max_length=200)),
                ("rule_description", models.TextField()),
                ("validation_logic", models.JSONField(help_text="JSON schema for validation")),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "export_compliance_rules",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(fields=["country_code", "product_category"], name="export_comp_country_31d3a3_idx"),
                    models.Index(fields=["is_active", "effective_date"], name="export_comp_is_acti_32eaf5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Commercial Invoice"),
                            ("CERTIFICATE_ORIGIN", "Certificate of Origin"),
                            ("PHYTOSANITARY", "Phytosanitary Certificate"),
                            ("PACKING_LIST", "Packing List"),
                            ("BILL_LADING", "Bill of Lading"),
                            ("EXPORT_LICENSE", "Export License"),
                            ("CUSTOMS_DECLARATION", "Customs Declaration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country_code", models.CharField(help_text="ISO 3166-1 alpha-3 country code", max_length=3)),
                (
                    "template_file",
                    models.FileField(
                        upload_to="export_docs/templates/",
                        validators=[django.core.validators.FileExtensionValidator(["html", "pdf", "docx"])],
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "export_document_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["document_type", "country_code"], name="export_docu_documen_578b8d_idx"),
                    models.Index(fields=["is_active"], name="export_docu_is_acti_7d7956_idx"),
                ],
                "unique_together": {("document_type", "country_code", "version")},
            },
        ),
        migrations.CreateModel(
            name="ExportDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("document_number", models.CharField(max_length=50, unique=True)),
                ("shipment_reference", models.CharField(blank=True, max_length=100)),
                ("destination_country", models.CharField(max_length=3)),
                ("origin_country", models.CharField(default="GHA", max_length=3)),
                ("product_description", models.TextField()),
                ("product_category", models.CharField(max_length=100)),
                ("hs_code", models.CharField(help_text="Harmonized System code", max_length=20)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("document_data", models.JSONField(help_text="Complete document data")),
                ("generated_file", models.FileField(blank=True, upload_to="export_docs/generated/")),
                ("digital_signature", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUBMITTED", "Submitted to Customs"),
                            ("ACCEPTED", "Accepted by Customs"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("compliance_checked", models.BooleanField(default=False)),
                ("compliance_issues", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submission_reference", models.CharField(blank=True, max_length=100)),
                ("customs_response", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="export_docs.documenttemplate"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "export_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.IntegerField()),
                ("document_data", models.JSONField()),
                ("generated_file", models.FileField(upload_to="export_docs/versions/")),
                ("change_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="export_docs.exportdocument"
                    ),
                ),
            ],
            options={
                "db_table": "export_document_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="CustomsSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("customs_system", models.CharField(max_length=100)),
                ("submission_reference", models.CharField(max_length=100, unique=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("response_received_at", models.DateTimeField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="export_docs.exportdocument",
                    ),
                ),
            ],
            options={
                "db_table": "customs_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exportdocument",
            index=models.Index(fields=["user", "status"], name="export_docu_user_id_90256c_idx"),
        ),
        migrations.AddIndex(
            model_name="exportdocument",
            index=models.Index(fields=["destination_country", "product_category"], name="export_docu_destina_c18db1_idx"),
        ),
        migrations.AddIndex(
            model_name="exportdocument",
            index=models.Index(fields=["document_number"], name="export_docu_documen_ee8b65_idx"),
        ),
        migrations.AddIndex(
            model_name="exportdocument",
            index=models.Index(fields=["created_at"], name="export_docu_created_6b010e_idx"),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["document", "version_number"], name="export_docu_documen_e875f0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_number")},
        ),
        migrations.AddIndex(
            model_name="customssubmission",
            index=models.Index(fields=["document", "status"], name="customs_sub_documen_974fd8_idx"),
        ),
        migrations.AddIndex(
            model_name="customssubmission",
            index=models.Index(fields=["submission_reference"], name="customs_sub_submiss_566635_idx"),
        ),
        migrations.AddIndex(
            model_name="customssubmission",
            index=models.Index(fields=["status", "next_retry_at"], name="customs_sub_status_26e98a_idx"),
        ),
    ]
