# Generated by Django 5.2.7 on 2025-12-04 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0002_field_crop_field_satelliteimagery_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropCalendar",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("crop_name", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("germination_days", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("vegetative_days", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("flowering_days", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("fruiting_days", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("maturity_days", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("planting_activities", models.JSONField(default=list)),
                ("growth_activities", models.JSONField(default=list)),
                ("harvest_activities", models.JSONField(default=list)),
                ("optimal_planting_months", models.JSONField(default=list, help_text="List of month numbers (1-12)")),
                ("climate_zones", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["crop_name", "variety"],
                "indexes": [
                    models.Index(fields=["crop_name"], name="scheduling__crop_na_1394c5_idx"),
                    models.Index(fields=["is_active"], name="scheduling__is_acti_210641_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("watering", "Watering"),
                            ("fertilizing", "Fertilizing"),
                            ("pest_control", "Pest Control"),
                            ("weeding", "Weeding"),
                            ("harvesting", "Harvesting"),
                            ("maintenance", "Maintenance"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_interval",
                    models.IntegerField(
                        default=1,
                        help_text="Interval for recurrence (e.g., every 2 weeks)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("recurrence_end_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                (
                    "reminder_time",
                    models.IntegerField(
                        default=60,
                        help_text="Minutes before due date to send reminder",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(blank=True, related_name="assigned_tasks", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="farms.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="farms.field",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_instances",
                        to="scheduling.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-priority"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="scheduling__user_id_21b07e_idx"),
                    models.Index(fields=["due_date"], name="scheduling__due_dat_ac6bbd_idx"),
                    models.Index(fields=["status"], name="scheduling__status_e54415_idx"),
                    models.Index(fields=["farm"], name="scheduling__farm_id_8d502a_idx"),
                    models.Index(fields=["field"], name="scheduling__field_i_771496_idx"),
                    models.Index(fields=["is_recurring"], name="scheduling__is_recu_91ca92_idx"),
                    models.Index(fields=["reminder_sent", "due_date"], name="scheduling__reminde_4fa6ad_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("planting", "Planting"),
                            ("watering", "Watering"),
                            ("fertilizing", "Fertilizing"),
                            ("pest_control", "Pest Control"),
                            ("weeding", "Weeding"),
                            ("harvesting", "Harvesting"),
                            ("maintenance", "Maintenance"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "default_reminder_time",
                    models.IntegerField(default=60, help_text="Default minutes before due date to send reminder"),
                ),
                ("is_public", models.BooleanField(default=False, help_text="Available to all users")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("checklist", models.JSONField(blank=True, default=list, help_text="List of subtasks")),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "name"],
                "indexes": [
                    models.Index(fields=["user"], name="scheduling__user_id_2936ad_idx"),
                    models.Index(fields=["category"], name="scheduling__categor_b3c221_idx"),
                    models.Index(fields=["is_public"], name="scheduling__is_publ_1b82b4_idx"),
                ],
            },
        ),
    ]
