# Generated by Django 5.2.7 on 2025-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_placed', 'Order Placed'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled')], default='order_created', max_length=50),
        ),
    ]
