# Generated by Django 5.2.7 on 2025-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_add_order_placed_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="escrow_id",
            field=models.CharField(blank=True, help_text="Escrow transaction ID", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, help_text="External payment ID", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.URLField(blank=True, help_text="Payment gateway URL"),
        ),
    ]
