# Generated by Django 5.2.7 on 2025-12-05 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alert_number", models.CharField(max_length=50, unique=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("WEATHER", "Weather Alert"),
                            ("PEST", "Pest Outbreak"),
                            ("DISEASE", "Disease Outbreak"),
                            ("FLOOD", "Flood Warning"),
                            ("DROUGHT", "Drought Warning"),
                            ("FIRE", "Fire Alert"),
                            ("SECURITY", "Security Threat"),
                            ("MARKET", "Market Disruption"),
                            ("OTHER", "Other Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("country", models.CharField(default="GHA", max_length=3)),
                ("regions", models.JSONField(blank=True, default=list, help_text="List of region names")),
                ("districts", models.JSONField(blank=True, default=list, help_text="List of district names")),
                ("coordinates", models.JSONField(blank=True, help_text="GeoJSON polygon for affected area", null=True)),
                ("response_guidelines", models.TextField(help_text="What people should do")),
                ("emergency_contacts", models.JSONField(default=dict, help_text="Emergency contact information")),
                ("resources", models.JSONField(blank=True, default=list, help_text="Available resources and support")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("broadcast_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("acknowledgment_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "emergency_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertAcknowledgment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("location", models.JSONField(blank=True, help_text="User location when acknowledged", null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_acknowledgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="emergency_response.emergencyalert",
                    ),
                ),
            ],
            options={
                "db_table": "alert_acknowledgments",
                "ordering": ["-acknowledged_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyGuideline",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "guideline_type",
                    models.CharField(
                        choices=[
                            ("WEATHER", "Weather Emergency"),
                            ("PEST", "Pest Management"),
                            ("DISEASE", "Disease Control"),
                            ("FLOOD", "Flood Response"),
                            ("DROUGHT", "Drought Management"),
                            ("FIRE", "Fire Safety"),
                            ("SECURITY", "Security Protocol"),
                            ("GENERAL", "General Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("immediate_actions", models.JSONField(help_text="List of immediate actions to take")),
                ("safety_measures", models.JSONField(help_text="Safety precautions")),
                ("resources_needed", models.JSONField(blank=True, default=list)),
                ("emergency_contacts", models.JSONField(default=dict)),
                ("support_services", models.JSONField(blank=True, default=list)),
                (
                    "applicable_regions",
                    models.JSONField(blank=True, default=list, help_text="List of applicable region names"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emergency_guidelines",
                "ordering": ["guideline_type", "title"],
                "indexes": [models.Index(fields=["guideline_type", "is_active"], name="emergency_g_guideli_1e6b3c_idx")],
            },
        ),
        migrations.CreateModel(
            name="IncidentAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("region", models.CharField(blank=True, max_length=100)),
                ("total_incidents", models.IntegerField(default=0)),
                ("incidents_by_type", models.JSONField(default=dict)),
                ("incidents_by_severity", models.JSONField(default=dict)),
                ("total_alerts", models.IntegerField(default=0)),
                ("alerts_by_type", models.JSONField(default=dict)),
                ("average_response_time", models.DurationField(blank=True, null=True)),
                ("verification_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("resolution_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("acknowledgment_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("common_patterns", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "incident_analytics",
                "ordering": ["-period_end"],
                "indexes": [
                    models.Index(fields=["period_start", "period_end"], name="incident_an_period__186fee_idx"),
                    models.Index(fields=["region"], name="incident_an_region_797573_idx"),
                ],
                "unique_together": {("period_start", "period_end", "region")},
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("report_number", models.CharField(max_length=50, unique=True)),
                ("reporter_contact", models.CharField(blank=True, max_length=20)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("WEATHER", "Weather Event"),
                            ("PEST", "Pest Infestation"),
                            ("DISEASE", "Disease Outbreak"),
                            ("FLOOD", "Flooding"),
                            ("DROUGHT", "Drought"),
                            ("FIRE", "Fire"),
                            ("THEFT", "Theft/Security"),
                            ("ACCIDENT", "Accident"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity_assessment",
                    models.CharField(
                        blank=True,
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        max_length=20,
                    ),
                ),
                ("location_description", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("photos", models.JSONField(blank=True, default=list, help_text="List of photo URLs")),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("VERIFIED", "Verified"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_reports",
                        to="emergency_response.emergencyalert",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incident_reports",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["alert_type", "severity"], name="emergency_a_alert_t_7e40de_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["status", "issued_at"], name="emergency_a_status_8a9a7a_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["country"], name="emergency_a_country_c1d704_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(fields=["created_at"], name="emergency_a_created_883a3c_idx"),
        ),
        migrations.AddIndex(
            model_name="alertacknowledgment",
            index=models.Index(fields=["alert", "acknowledged_at"], name="alert_ackno_alert_i_9696cc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alertacknowledgment",
            unique_together={("alert", "user")},
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(fields=["incident_type", "status"], name="incident_re_inciden_62e8b5_idx"),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(fields=["reporter", "reported_at"], name="incident_re_reporte_5c7698_idx"),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(fields=["region", "district"], name="incident_re_region_c04fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(fields=["status", "reported_at"], name="incident_re_status_f1ea51_idx"),
        ),
    ]
