# Generated by Django 5.2.7 on 2025-12-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField()),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_percentage", models.IntegerField(default=0, help_text="Percentage of users to enable (0-100)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(blank=True, related_name="feature_flags", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "admin_feature_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric_name", models.CharField(db_index=True, max_length=255)),
                ("metric_value", models.FloatField()),
                ("metric_unit", models.CharField(max_length=50)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "admin_platform_metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["metric_name", "-timestamp"], name="admin_platf_metric__5e7ed3_idx"),
                    models.Index(fields=["category", "-timestamp"], name="admin_platf_categor_db134d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("permission_change", "Permission Change"),
                            ("config_change", "Configuration Change"),
                            ("moderation", "Moderation Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("changes", models.JSONField(default=dict, help_text="Before/after values")),
                ("metadata", models.JSONField(default=dict, help_text="Additional context")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="admin_audit_timesta_5c0429_idx"),
                    models.Index(fields=["user", "-timestamp"], name="admin_audit_user_id_235736_idx"),
                    models.Index(fields=["action_type", "-timestamp"], name="admin_audit_action__0ea3f8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "moderation_type",
                    models.CharField(
                        choices=[
                            ("post", "Community Post"),
                            ("comment", "Comment"),
                            ("product", "Marketplace Product"),
                            ("review", "Product Review"),
                            ("message", "Private Message"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged for Review"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0, help_text="Higher priority items reviewed first")),
                ("report_reason", models.TextField()),
                ("automated_flags", models.JSONField(default=dict, help_text="Automated detection flags")),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_moderation_queue",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="admin_moder_status_0368a4_idx"),
                    models.Index(fields=["-priority", "-created_at"], name="admin_moder_priorit_b2a851_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("incident_type", models.CharField(db_index=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("detection_method", models.CharField(max_length=100)),
                ("indicators", models.JSONField(default=dict)),
                ("investigation_notes", models.TextField(blank=True)),
                ("resolution", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_security_incidents",
                "ordering": ["-severity", "-detected_at"],
                "indexes": [
                    models.Index(fields=["status", "-detected_at"], name="admin_secur_status_fe1e17_idx"),
                    models.Index(fields=["severity", "-detected_at"], name="admin_secur_severit_a84ac9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_system_configuration",
                "ordering": ["category", "key"],
                "indexes": [models.Index(fields=["category", "key"], name="admin_syste_categor_5d1be9_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_type", models.CharField(db_index=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_user_activity",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["user", "-timestamp"], name="admin_user__user_id_616562_idx"),
                    models.Index(fields=["activity_type", "-timestamp"], name="admin_user__activit_3af0ba_idx"),
                ],
            },
        ),
    ]
