# Generated by Django 5.2.7 on 2025-12-05 00:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("effective_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(fields=["from_currency", "to_currency"], name="payment_exc_from_cu_32251f_idx"),
                    models.Index(fields=["effective_date"], name="payment_exc_effecti_3a9a14_idx"),
                ],
                "unique_together": {("from_currency", "to_currency", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("payout", "Payout"),
                            ("escrow_hold", "Escrow Hold"),
                            ("escrow_release", "Escrow Release"),
                        ],
                        default="payment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("ussd", "USSD"),
                            ("qr", "QR Code"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("fee", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gateway", models.CharField(default="paystack", max_length=50)),
                ("gateway_reference", models.CharField(blank=True, max_length=200)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("order_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("escrow_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("receipt_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("issued_by", models.CharField(default="AgroBridge", max_length=200)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("items", models.JSONField(default=list)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="receipts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="receipt", to="payment.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Escrow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(db_index=True, max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("held", "Held"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=100)),
                ("auto_release_days", models.IntegerField(default=7)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("held_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="escrow_sales", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "hold_transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escrow_holds",
                        to="payment.transaction",
                    ),
                ),
                (
                    "release_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escrow_releases",
                        to="payment.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(db_index=True, max_length=100, unique=True)),
                ("reason", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buyer_favor", "Buyer Favor"),
                            ("seller_favor", "Seller Favor"),
                            ("partial_refund", "Partial Refund"),
                            ("no_action", "No Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("refund_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "against",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_refunds",
                        to="payment.transaction",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="disputes", to="payment.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "status"], name="payment_tra_user_id_33fe33_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["reference"], name="payment_tra_referen_2a6f6d_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["gateway_reference"], name="payment_tra_gateway_14c3ca_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["order_id"], name="payment_tra_order_i_c6a3d5_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["created_at"], name="payment_tra_created_0d0f1d_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["issued_to"], name="payment_pay_issued__5194cc_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["receipt_number"], name="payment_pay_receipt_99445d_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(fields=["issued_at"], name="payment_pay_issued__524ab7_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["buyer", "status"], name="payment_esc_buyer_i_ece4a9_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["seller", "status"], name="payment_esc_seller__75daca_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["order_id"], name="payment_esc_order_i_f660a5_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["status"], name="payment_esc_status_06ae7b_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["raised_by", "status"], name="payment_dis_raised__af1447_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["transaction"], name="payment_dis_transac_dfed44_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status"], name="payment_dis_status_242881_idx"),
        ),
    ]
