# Generated by Django 5.2.7 on 2025-12-04 17:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("delete_profile", models.BooleanField(default=True)),
                ("delete_activity", models.BooleanField(default=True)),
                ("delete_content", models.BooleanField(default=True)),
                ("anonymize_data", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Data Export"),
                            ("profile", "Profile Data Only"),
                            ("activity", "Activity Data Only"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("download_url", models.URLField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("newsletter_subscription", models.BooleanField(default=True)),
                ("marketplace_notifications", models.BooleanField(default=True)),
                ("order_notifications", models.BooleanField(default=True)),
                ("farm_alerts", models.BooleanField(default=True)),
                ("weather_alerts", models.BooleanField(default=True)),
                ("price_alerts", models.BooleanField(default=True)),
                ("community_notifications", models.BooleanField(default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tw", "Twi"), ("ha", "Hausa"), ("fr", "French")],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("GHS", "Ghana Cedi"), ("NGN", "Nigerian Naira"), ("EUR", "Euro")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("data_sharing_consent", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("analytics_consent", models.BooleanField(default=True)),
                ("dnd_enabled", models.BooleanField(default=False)),
                ("dnd_start_time", models.TimeField(blank=True, null=True)),
                ("dnd_end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="newsletter_subscription",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sms_notifications",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, help_text="Short bio about the user", max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("friends", "Friends Only"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_contact_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_media_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("profile_update", "Profile Update"),
                    ("preferences_update", "Preferences Update"),
                    ("password_change", "Password Change"),
                    ("avatar_upload", "Avatar Upload"),
                    ("product_view", "Product View"),
                    ("search", "Search Activity"),
                    ("data_export_request", "Data Export Request"),
                    ("data_deletion_request", "Data Deletion Request"),
                    ("profile_view", "Profile View"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["city", "state", "country"], name="users_userp_city_8b3a94_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["specialization"], name="users_userp_special_d3686a_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["farm_experience"], name="users_userp_farm_ex_f5cc2d_idx"),
        ),
        migrations.AddField(
            model_name="datadeletionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="deletion_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dataexportrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="export_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
