# Generated by Django 5.2.7 on 2025-12-04 20:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_currency", models.CharField(default="GHS", max_length=3)),
                ("target_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["base_currency", "target_currency", "date"], name="financial_e_base_cu_886ef9_idx")
                ],
                "unique_together": {("base_currency", "target_currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("crop_sales", "Crop Sales"),
                            ("livestock_sales", "Livestock Sales"),
                            ("product_sales", "Product Sales"),
                            ("service_income", "Service Income"),
                            ("subsidy", "Government Subsidy"),
                            ("loan", "Loan"),
                            ("investment", "Investment"),
                            ("other_income", "Other Income"),
                            ("seeds", "Seeds & Planting Materials"),
                            ("fertilizer", "Fertilizers"),
                            ("pesticides", "Pesticides & Herbicides"),
                            ("equipment", "Equipment Purchase"),
                            ("equipment_maintenance", "Equipment Maintenance"),
                            ("fuel", "Fuel & Energy"),
                            ("labor", "Labor Costs"),
                            ("irrigation", "Irrigation"),
                            ("feed", "Animal Feed"),
                            ("veterinary", "Veterinary Services"),
                            ("transport", "Transportation"),
                            ("storage", "Storage"),
                            ("insurance", "Insurance"),
                            ("rent", "Land Rent"),
                            ("utilities", "Utilities"),
                            ("marketing", "Marketing"),
                            ("loan_repayment", "Loan Repayment"),
                            ("taxes", "Taxes"),
                            ("other_expense", "Other Expense"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Period"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("exceeded", "Exceeded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=80,
                        help_text="Alert when spending reaches this percentage",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MinValueValidator(100),
                        ],
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                ("farm_id", models.UUIDField(blank=True, help_text="Related farm ID", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="budgets", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="financial_b_user_id_8f6363_idx"),
                    models.Index(fields=["start_date", "end_date"], name="financial_b_start_d_b361a3_idx"),
                    models.Index(fields=["category"], name="financial_b_categor_f2b257_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("record_type", models.CharField(choices=[("income", "Income"), ("expense", "Expense")], max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("crop_sales", "Crop Sales"),
                            ("livestock_sales", "Livestock Sales"),
                            ("product_sales", "Product Sales"),
                            ("service_income", "Service Income"),
                            ("subsidy", "Government Subsidy"),
                            ("loan", "Loan"),
                            ("investment", "Investment"),
                            ("other_income", "Other Income"),
                            ("seeds", "Seeds & Planting Materials"),
                            ("fertilizer", "Fertilizers"),
                            ("pesticides", "Pesticides & Herbicides"),
                            ("equipment", "Equipment Purchase"),
                            ("equipment_maintenance", "Equipment Maintenance"),
                            ("fuel", "Fuel & Energy"),
                            ("labor", "Labor Costs"),
                            ("irrigation", "Irrigation"),
                            ("feed", "Animal Feed"),
                            ("veterinary", "Veterinary Services"),
                            ("transport", "Transportation"),
                            ("storage", "Storage"),
                            ("insurance", "Insurance"),
                            ("rent", "Land Rent"),
                            ("utilities", "Utilities"),
                            ("marketing", "Marketing"),
                            ("loan_repayment", "Loan Repayment"),
                            ("taxes", "Taxes"),
                            ("other_expense", "Other Expense"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("description", models.TextField()),
                ("transaction_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("receipt_image", models.ImageField(blank=True, null=True, upload_to="financial/receipts/")),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("farm_id", models.UUIDField(blank=True, help_text="Related farm ID", null=True)),
                ("order_id", models.UUIDField(blank=True, help_text="Related marketplace order ID", null=True)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "record_type"], name="financial_f_user_id_57c14e_idx"),
                    models.Index(fields=["user", "transaction_date"], name="financial_f_user_id_ad5543_idx"),
                    models.Index(fields=["category"], name="financial_f_categor_669852_idx"),
                    models.Index(fields=["transaction_date"], name="financial_f_transac_cd2ea7_idx"),
                    models.Index(fields=["farm_id"], name="financial_f_farm_id_1dea5f_idx"),
                    models.Index(fields=["order_id"], name="financial_f_order_i_eddecf_idx"),
                ],
            },
        ),
    ]
