# Generated by Django 5.2.7 on 2025-10-23 13:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.JSONField(default=dict, help_text='Coordinates, address, and location details')),
                ('size_hectares', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('farm_type', models.CharField(choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock Farming'), ('poultry', 'Poultry Farming'), ('mixed', 'Mixed Farming'), ('organic', 'Organic Farming'), ('greenhouse', 'Greenhouse Farming'), ('aquaculture', 'Aquaculture')], max_length=20)),
                ('established_date', models.DateField()),
                ('certification', models.CharField(choices=[('none', 'No Certification'), ('organic', 'Organic Certified'), ('gap', 'Good Agricultural Practices'), ('fair_trade', 'Fair Trade'), ('rainforest', 'Rainforest Alliance')], default='none', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow public visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('tractor', 'Tractor'), ('plow', 'Plow'), ('harrow', 'Harrow'), ('seeder', 'Seeder'), ('sprayer', 'Sprayer'), ('harvester', 'Harvester'), ('irrigation', 'Irrigation System'), ('generator', 'Generator'), ('tools', 'Hand Tools'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=20)),
                ('is_operational', models.BooleanField(default=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hours_used', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('specifications', models.JSONField(default=dict, help_text='Technical specifications')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('plants_per_hectare', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('season', models.CharField(choices=[('dry', 'Dry Season'), ('wet', 'Wet Season'), ('year_round', 'Year Round')], max_length=20)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('chickens', 'Chickens'), ('ducks', 'Ducks'), ('turkeys', 'Turkeys'), ('rabbits', 'Rabbits'), ('fish', 'Fish'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tag_numbers', models.TextField(blank=True, help_text='Comma-separated tag numbers')),
                ('average_age_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('purpose', models.CharField(choices=[('meat', 'Meat Production'), ('dairy', 'Dairy Production'), ('eggs', 'Egg Production'), ('breeding', 'Breeding'), ('draft', 'Draft Work'), ('pets', 'Pets/Companion'), ('mixed', 'Mixed Purpose')], max_length=20)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('sick', 'Sick'), ('quarantine', 'Quarantine')], default='good', max_length=20)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_production', models.JSONField(default=dict, help_text='Monthly production data (milk, eggs, etc.)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('planting', 'Planting'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pest_control', 'Pest Control'), ('weeding', 'Weeding'), ('pruning', 'Pruning'), ('harvesting', 'Harvesting'), ('feeding', 'Animal Feeding'), ('vaccination', 'Vaccination'), ('breeding', 'Breeding'), ('maintenance', 'Equipment Maintenance'), ('inspection', 'Inspection'), ('treatment', 'Treatment'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('materials_used', models.JSONField(default=list, help_text='List of materials and quantities')),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('results', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.farm')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.livestock')),
            ],
            options={
                'verbose_name_plural': 'Farm Activities',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['owner'], name='farms_farm_owner_i_194369_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farm_type'], name='farms_farm_farm_ty_fc3da7_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['is_active'], name='farms_farm_is_acti_0f0498_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['created_at'], name='farms_farm_created_c33b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['farm'], name='farms_equip_farm_id_d0a90a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='farms_equip_equipme_a41322_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['condition'], name='farms_equip_conditi_7393f5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_operational'], name='farms_equip_is_oper_cc48ee_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['farm'], name='farms_crop_farm_id_8a14ff_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['status'], name='farms_crop_status_d914ff_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['planting_date'], name='farms_crop_plantin_197de9_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['expected_harvest_date'], name='farms_crop_expecte_3de32f_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['farm'], name='farms_lives_farm_id_43bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['animal_type'], name='farms_lives_animal__c0acf1_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['health_status'], name='farms_lives_health__af1b57_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['acquisition_date'], name='farms_lives_acquisi_26b3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['farm'], name='farms_farma_farm_id_bdacb7_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['activity_type'], name='farms_farma_activit_f96ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['status'], name='farms_farma_status_a1dbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['scheduled_date'], name='farms_farma_schedul_34ed32_idx'),
        ),
        migrations.AddIndex(
            model_name='farmactivity',
            index=models.Index(fields=['priority'], name='farms_farma_priorit_42a670_idx'),
        ),
    ]
