# Generated by Django 5.2.7 on 2025-12-04 17:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("boundary_geojson", models.JSONField(help_text="GeoJSON polygon defining field boundaries")),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loam", "Loam"),
                            ("silt", "Silt"),
                            ("peat", "Peat"),
                            ("chalk", "Chalk"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("14")),
                        ],
                    ),
                ),
                ("elevation_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "slope_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("none", "No Irrigation"),
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood Irrigation"),
                            ("furrow", "Furrow Irrigation"),
                            ("center_pivot", "Center Pivot"),
                            ("manual", "Manual Watering"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("has_drainage", models.BooleanField(default=False)),
                ("has_fencing", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_cultivation_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="farms.farm"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="crop",
            name="field",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific field where crop is planted",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="farms.field",
            ),
        ),
        migrations.CreateModel(
            name="SatelliteImagery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "satellite_name",
                    models.CharField(
                        choices=[
                            ("sentinel2", "Sentinel-2"),
                            ("landsat8", "Landsat 8"),
                            ("landsat9", "Landsat 9"),
                            ("modis", "MODIS"),
                            ("planet", "Planet"),
                            ("worldview", "WorldView"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagery_type",
                    models.CharField(
                        choices=[
                            ("optical", "Optical"),
                            ("radar", "Radar"),
                            ("multispectral", "Multispectral"),
                            ("hyperspectral", "Hyperspectral"),
                            ("thermal", "Thermal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("acquisition_date", models.DateTimeField()),
                (
                    "cloud_coverage_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "resolution_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0.1"))]
                    ),
                ),
                ("image_url", models.URLField(blank=True, help_text="URL to the satellite image")),
                ("thumbnail_url", models.URLField(blank=True, help_text="URL to image thumbnail")),
                (
                    "vegetation_indices",
                    models.JSONField(default=dict, help_text="Calculated vegetation indices (NDVI, EVI, etc.)"),
                ),
                (
                    "crop_health_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("stress_indicators", models.JSONField(default=list, help_text="List of detected stress indicators")),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="satellite_images", to="farms.field"
                    ),
                ),
            ],
            options={
                "ordering": ["-acquisition_date"],
            },
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["farm"], name="farms_field_farm_id_3159d8_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["is_active"], name="farms_field_is_acti_2861cd_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["soil_type"], name="farms_field_soil_ty_7e0d45_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["irrigation_type"], name="farms_field_irrigat_ee26d1_idx"),
        ),
        migrations.AddIndex(
            model_name="satelliteimagery",
            index=models.Index(fields=["field"], name="farms_satel_field_i_f5315c_idx"),
        ),
        migrations.AddIndex(
            model_name="satelliteimagery",
            index=models.Index(fields=["satellite_name"], name="farms_satel_satelli_15bd0c_idx"),
        ),
        migrations.AddIndex(
            model_name="satelliteimagery",
            index=models.Index(fields=["acquisition_date"], name="farms_satel_acquisi_c1ac4f_idx"),
        ),
        migrations.AddIndex(
            model_name="satelliteimagery",
            index=models.Index(fields=["is_processed"], name="farms_satel_is_proc_5e5513_idx"),
        ),
    ]
